### ISSUE TITLE
Wrong file/MD5?

### ISSUE THREAD

**Issue by SmurgBurglar** [GhostlyDark/OoT-Reloaded-SoH#1]
Is "Legend of Zelda, The - Ocarina of Time - Master Quest (USA) (Debug Version).z64 (MD5: 8ca71e87de4ce5e9f6ec916202a623e9)" correct? i cant find anything like that.

**Comment by GhostlyDark** [comment]
Follow the instructions of Ship of Harkinian if you're unsure what files to use. The hash is correct.
![image](https://github.com/GhostlyDark/OoT-Reloaded-SoH/assets/31742919/1dbd514d-0cec-470b-8931-a6ce6d2dbad5)
