### ISSUE TITLE
Mapping Glide64 textures to SoH

### ISSUE THREAD

**Issue by Tokobotenkai** [GhostlyDark/OoT-Reloaded-SoH#10]
I wanted to contact you directly but didn't see how.

I was wondering if there's a way to map the Glide64 PNG files to the SoH ones?

https://emulationking.com/djipis-2016-3ds-oot/

I am looking at the PNG files here and wondering if I could replace the PNG files from the original OTR file generated from the ROM.

**Comment by GhostlyDark** [comment]
There is no easy way to do this and Ship of Harkinian is also changing how the textures are named with an upcoming stable release. Djipi is working on a port himself, though there is no ETA when his texture packs are going to be available for SoH.
