### ISSUE TITLE
Textures need to be renamed to Debug MQ names to work on future versions of SoH

### ISSUE THREAD

**Issue by crustySenpai** [GhostlyDark/OoT-Reloaded-SoH#11]
purplehato on the soh discord posted a powershell script that automatically renames textures to work with 7.1.1 and onwards
currently testing it and it seems to be working only a handfull of textures where working before

Here is the post from him:

I created this tool for those who work on Texture Packs and need to update them for the upcoming SoH version (starting from 7.1.1 onwards). In this new version, texture names will be standardized to use the Debug MQ names for every supported ROM. This means there's no longer a need to create patches for specific versions like PAL 1.1 or Vanilla GC.

Using this tool is quite straightforward:

1. Ensure that you can run PowerShell scripts on your computer
2. Create a backup of your original texture folder, just to be safe
3. Run the script and provide the path to the folder you want to convert
4. Copy your newly renamed textures to a freshly extracted Dev Build from Retro, and you're good to go
5. Make sure not to include the manifest.json file when copying 😄

https://cdn.discordapp.com/attachments/1089931043420778516/1162356146053587044/texturePackRename.ps1

link to the post:
https://discord.com/channels/808039310850130000/1089931043420778516/1162356146837913790

Just figured it might be useful info and worth to be mentioned

**Comment by Archez** [comment]
One more change coming before the next release is the following: https://github.com/HarbourMasters/Shipwright/pull/3191
Where any scene that does not have a unique MQ variant will now be placed in a `scenes/shared/` folder, so that those scenes only need to have textures set once. the `scenes/nonmq/` and `scenes/mq/` folders will strictly be the dungeons only.

That powershell script may be updated to handle this change, just need to see if they are able to get it ready before the next release.

**Comment by Archez** [comment]
SoH 8.0.0 is now released, and we have prepared a tool for you to use to update your pack https://github.com/PurpleHato/SoHTexturePackUpdater

**Comment by GhostlyDark** [comment]
Renaming is done.

**Comment by Hackmodford** [comment]
Does this work in macOS?

I've got SOH 8.0 and downloaded the 10.4.1 version of the otr files. 
My SoH doesn't load the textures.

**Comment by Hackmodford** [comment]
Figured it out. While the mods folder had read access, the files themselves did not.

**Comment by jmonster** [comment]
@Hackmodford **THANK YOU**.
