### ISSUE TITLE
stuttering

### ISSUE THREAD

**Issue by Scarecrow64** [GhostlyDark/OoT-Reloaded-SoH#12]
About the stuttering caused by using the texture pack. Is there anything new to resolve this problem? I spoke with developers of "ship", they say that there are 2 problems. That he would like to make a dynamic loading system to solve this. and the texture pack is not very optimized, it is more than 20 GB. Would it be possible to have lighter versions of the texture pack so that loading is instantaneous? thanks

**Comment by GhostlyDark** [comment]
The devs like to blame me for all performance issues, but it's only partially true. There are two things that I can do to directly influence performance:
1) OTR files can be compressed or uncompressed, the latter decreasing stuttering at the expense of a much larger file size. Currently, all release files are **uncompressed**.
2) The HD version of the pack has textures downscaled to a maximum of 8x the original texture resolution. While this technically decreases visual fidelity, it can still look good and improve performance.

The 4K version is just the source files untouched, with no concern about stuttering issues. The HD version is the "optimized" release. There's not really anything else I can do to improve upon this, other than to further decrease texture sizes, which gets very noticable below 8x however.

SoH v8.0.0 has decreased the number of duplicate textures, but there is still a lot of "junk" in the files, e.g. a dungeon scene needing tons of duplicates for each and every room. The way textures are converted and loaded in doesn't allow for something like DDS textures to be implemented - which could have been used to pretty much kill any stuttering issues. Prefetching instead wouldn't be a solution either as it would require a ton of RAM.

The stuttering is comparable to GLideN64 using no cache, which is about the worst performance you can get with HD textures on any of the three platforms you can play OoT Reloaded on (GLideN64 HTS, Dolphin DDS, SoH OTR).

**Comment by Scarecrow64** [comment]
Thank you for these details. I tried the HD version and I obviously don't have any stutering. If the 4k version are the original source files, would it be possible to make a lightweight 4k version simply by compressing the textures sufficiently without affecting their resolution? 

_"4K version is just the source files untouched, with no concern about stuttering issues."_
Are you saying that the 4k version has no stutering problem? However I looked on YouTube everyone who uses the 4k pack has this problem

**Comment by GhostlyDark** [comment]
Textures have to be converted to a format that SoH can work with. It's not reading PNG files. Similarly to GLideN64, which converts textures to BMP, the only way to improve performance is to downscale the images. Compressing them - lossless or not - will do absolutely nothing for the final texture size, which in turn leaves performance unaffected.

4K definitely does stutter. What I was trying to say is that performance isn't really considered when creating textures (aside from not using completely insane sizes).
