### ISSUE TITLE
King Dodongo lava textures need updates

### ISSUE THREAD

**Issue by Archez** [GhostlyDark/OoT-Reloaded-SoH#13]
On the SoH side I am repairing the lava effects for King Dodongo's room via https://github.com/HarbourMasters/Shipwright/pull/3434

With 8.0.0 we fixed an issue where one of the lava textures had the width and height values reversed. This means you will need to remake that texture to match the correct height/width ratio.

To make the lava effects work, in the code it requires that some pixel data is copied from one texture over another in-game. This means that all the lava textures need to have a similar scale.

The textures of concern and their original sizes are the following:
`scenes/shared/ddan_boss_scene/gDodongosCavernBossLaveFloorTex` - width: 32, height: 64
`ovlerlays/ovl_Boss_Dodongo/sLavaFloorLavaTex` - ~~width: 64, height 64~~ Edit: now width: 32, height 64 after https://github.com/HarbourMasters/Shipwright/pull/3449
`ovlerlays/ovl_Boss_Dodongo/sLavaFloorRockTex` - width: 32, height 64

So for example if you scale one of these by 8x, then all of them need to be scaled the same.

In the linked PR I used your textures (after fixing the scaling on my end) as reference.

**Comment by GhostlyDark** [comment]
Why is `sLavaFloorLavaTex` 64x64? All emulator dumps for these are 32x64, so it doesn't seem correct to me.
I did take care of the texture resolutions via 716996329b9cc115a14fa44596931f4791f85165. Let me know if there's anything else I should adjust.

**Comment by Archez** [comment]
> Why is `sLavaFloorLavaTex` 64x64? All emulator dumps for these are 32x64, so it doesn't seem correct to me.

I dug into it, and it seems the size was set by decomp, but the game code only reads 32x64 pixels worth of data from this texture. It's safe to say this is probably just an error in the texture size that can be corrected.

I have done that here <https://github.com/HarbourMasters/Shipwright/pull/3449>, once that is in you can get an updated manifest.json that has the corrected height/width values.

So now `sLavaFloorLavaTex` is basically a copy of `gDodongosCavernBossLaveFloorTex`

**Comment by GhostlyDark** [comment]
7ac2996
