### ISSUE TITLE
[Feature Request] Forest Medallion Symbol N64 Version Full Restoration, and Alternative Newer Symbol OTR.

### ISSUE THREAD

**Issue by PeeMoldy** [GhostlyDark/OoT-Reloaded-SoH#14]
You have done a wonderful job on this Texture Pack. I would like to make a request. Is there way you could completely restore all instances of the N64's Forest Medallion Symbol's 4 sided pinwheel shape? I've noticed that some of the textures still have the newer 3 sided pinwheel shape, while others retain the 4 sided design. And maybe you could make an Alternative Texture OTR like you did with the Gerudo Symbols of the Old Sun and Crescent Moon vs. the New Cobra Back symbol to allow only the 3 sided design to appear for those who prefer the newer design?

Again great work... This is what I'm talking about btw:

![fts](https://github.com/GhostlyDark/OoT-Reloaded-SoH/assets/152383944/4bb09282-a2de-4bce-81f2-cc3b5efd0fbc)

**Comment by GhostlyDark** [comment]
I think it's best to remake the assets using the original style, not the 3DS one. Staying close to the original visuals should always be the priority.

The current textures are all over the place, since they are based on different assets from different artists. I'd need to gain some serious drawing skills first if I where to replace them myself, so any contributions are much appreciated.

**Comment by PeeMoldy** [comment]
> I think it's best to remake the assets using the original style, not the 3DS one. Staying close to the original visuals should always be the priority.
> 
> The current textures are all over the place, since they are based on different assets from different artists. I'd need to gain some serious drawing skills first if I where to replace them myself, so any contributions are much appreciated.

I agree. I wish I had those art skills. Still learning GIMP and I want to look into Krita. It's almost like engineering, you gotta get those angles in the correct alignment. I will look for art master volunteers though.

**Comment by PeeMoldy** [comment]
That is sweet!
