### ISSUE TITLE
what is name of the font used?

### ISSUE THREAD

**Issue by resinate** [GhostlyDark/OoT-Reloaded-SoH#15]
im looking at what font is for names of towns or action 1-8
i wanna apply the same font for letters-numbers and timers as well

**Comment by PeeMoldy** [comment]
Have you a screenshot of this font?

**Comment by GhostlyDark** [comment]
The original game fonts are:
- Chiaro Std B (in-game dialog, rupee count/timer, logo subtitles, menu titles, dungeon titles on the map screen, location titles when entering an area...aka most things)
- KokinEdo Std EB (Boss titles: Name of the boss)
- RocknRoll Std Semi-Bold (Boss title descriptions, possibly the current location on the map screen too)
- RodinPro B (File Select)

https://shedevr.org.ru/zelda64rus/media-fonts.html

The action prompts, aka the A button text including the action numbers, don't use a font. In the original game, they are just pixel artwork. The HD ones are (heavily cleaned up) upscales of those using PixelPerfect ESRGAN.
