### ISSUE TITLE
SKYBOX, SELECT ITEM/EQUIPMENT/QUEST STATUS/MAP, AND INTRO GRAPHICS

### ISSUE THREAD

**Issue by Solid-Snake-Plissken** [GhostlyDark/OoT-Reloaded-SoH#18]
Is there a way you could make these separate downloads? They are the best part of your work and deserve to be enjoyed separately

**Comment by GhostlyDark** [comment]
There are no plans to make the texture pack more modular as that would increase the maintenance effort.
