### ISSUE TITLE
Environment textures not changing

### ISSUE THREAD

**Issue by jojoharry16** [GhostlyDark/OoT-Reloaded-SoH#19]
First and foremost, thanks to everyone working on this project. I realise it's a voluntary community effort and I want to emphasize that even if this issue is not fixed I am still grateful to anyone and everyone involved.

Now for the issue, I added all files to the mods folder of SoH, and most textures update as they should (text is crisp, trees and rocks are sharp, character textures are updated, etc.) but the environment textures, like the ground and walls, are simply not changed from their N64 versions.

## Examples
Default SoH:
![image](https://github.com/GhostlyDark/OoT-Reloaded-SoH/assets/39400627/437bb3f8-f553-44ca-bf9b-4f993234caf5)

Reloaded:
![image](https://github.com/GhostlyDark/OoT-Reloaded-SoH/assets/39400627/da4b63bb-6d09-4bb4-aa41-362cc46aaa64)

This is where I put the textures, and I also tested with only the first .otr file (that's why the others are highlighted, they were recently re-added)
![image](https://github.com/GhostlyDark/OoT-Reloaded-SoH/assets/39400627/8ecde103-e8ff-4bc9-8d18-5da2edbe462a)

Any and all help would be greatly appreciated. :)

**Comment by GhostlyDark** [comment]
What version of SoH are you using?

**Comment by jojoharry16** [comment]
Turns out I had version 7.1.1 installed. Updated to 8.0.5 and all textures are as God intended.

![image](https://github.com/GhostlyDark/OoT-Reloaded-SoH/assets/39400627/7bc14200-c1b8-44fb-bcd4-7b79b934b838)
