### ISSUE TITLE
Light arrow item name FRA typo

### ISSUE THREAD

**Issue by nodj** [GhostlyDark/OoT-Reloaded-SoH#20]
This is about `/textures/item_name_static/gLightArrowItemNameFRATex.png`

It should read "Flèche de Lumière (4MP)"

Others arrows looks OK, as an example `/textures/item_name_static/gIceArrowItemNameFRATex.png` looks fine.

**Comment by GhostlyDark** [comment]
Fixed to `Flèche de Lumière (4PM)` via 4923fd776ffe601e3b2bcbbe51a2932a2b5c4efc.
