### ISSUE TITLE
Small letter i with circumflex replaced by a capital i with circumflex in dialogs

### ISSUE THREAD

**Issue by nodj** [GhostlyDark/OoT-Reloaded-SoH#21]
I have a hard time describing this correctly as I don't know how fonts works in game, but basically as the title says, the `î` character is always replaced by a `Î` character.

- I've only played in FRA language
- I experienced this ~10 times in the full game, as this character occurs not so frequently.
- one such occurrence is in the first dialog **In french** with the owl (Kaepora Gaebora ?) the first time Links enters Hyrule.

I see in the files that there is a `gMsgChar81LatinCapitalLetterIWithCircumflexTex` texture, but I don't see a corresponding `gMsgChar81LatinSmallLetterIWithCircumflexTex`. Is there a replacement done by the game because of a missing texture ? IDK at all how things works to diagnostic the issue...

**Comment by nodj** [comment]
Here is an SoH save file to repro easily.
- game must be in French
- load that save file (you are entering hyrule from the kokiri vilage)
- run forward and get interrupted by the owl
- the last dialogue page contains a broken `î`
[file3.zip](https://github.com/user-attachments/files/15540773/file3.zip)
![i-with-circumflex-example](https://github.com/GhostlyDark/OoT-Reloaded-SoH/assets/7957601/7910d98d-7948-4cf6-a37e-2972268f7510)

**Comment by GhostlyDark** [comment]
This is a bug with the GameCube ROM text. Instead of î, it shows Á. I wanted to work around this by using a correct HD texture, but made the mistake to use Î instead of its lowercase variant. Corrected via bff3e3790e5cd6756df71a715c3384e98693e517.

As with the other mistakes you pointed out, thank you for doing so.

**Comment by nodj** [comment]
my pleasure ! thank you for the amazing work! OOT really shines nowadays thanks to projects like yours !
