### ISSUE TITLE
Some missing textures in the global Options menu, Language section

### ISSUE THREAD

**Issue by nodj** [GhostlyDark/OoT-Reloaded-SoH#22]
The Language section is not re-textured (title and values, any language)

![missing-option-language-textures](https://github.com/GhostlyDark/OoT-Reloaded-SoH/assets/7957601/bc4562cc-aad4-4f1d-96c7-c1c3af248951)

**Comment by GhostlyDark** [comment]
Should be covered by af005b5726d41a7ffa3bb90e096ea0815dd6271a.
