### ISSUE TITLE
Smaller Texture Size

### ISSUE THREAD

**Issue by rossimo** [GhostlyDark/OoT-Reloaded-SoH#3]
Is there a way I can generate a lower resolution mod file (say, 720p) for the Steam Deck? The texture pack looks great, but I'm hitting stutters on the Steam Deck when switching zones and entering the pause menu.

**Comment by GhostlyDark** [comment]
Downscaling the textures won't really fix the stuttering issue. OTR files unfortunately use compression, which is the main reason as to why the game is stuttering (CPU has to decompress the textures on the fly). There is no option to use uncompressed OTR files, so it's best to pester the SoH developers about it.

**Comment by rossimo** [comment]
I resized the high-res PNGs to 4x the size found in the original manifest _before_ creating an OTR, and the game runs smoothly now. The new Deck-friendly OTR file is 600MB. For posterity, here's my script.

`index.ts`
```
import fs from 'fs';
import { glob } from "glob";
import sharp from 'sharp';
import path from 'path';

const main = async () => {
    const source = './OoT-Reloaded-SoH-master/OoT Reloaded (SoH)';
    const manifest = JSON.parse(fs.readFileSync('./original/oot/manifest.json').toString());

    const files = await glob(`${source}/**/*.png`, {});
    console.log(`Found ${files.length} files`);

    let count = 0;

    for (const file of files) {
        const name = path.relative(source, file).replace('.png', '');
        const info = manifest[name.replace(/\\/g, '/')];
        if (info) {
            const buffer = fs.readFileSync(file);
            if (buffer.length > 0) {
                await sharp(buffer)
                    .resize({ width: info.textureWidth, height: info.textureHeight })
                    .toFile(file);
            }
        }

        if (++count % 100 == 0) {
            console.log(`Processed ${count} files`);
        }
    }

    if (count % 100 != 0) {
        console.log(`Processed ${count} files`);
    }
};

main().catch(err => {
    console.error(err);
    process.exit(1);
})
```

`package.json`
```
{
  "name": "small-oot",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "start": "ts-node src/index.ts"
  },
  "dependencies": {
    "@types/node": "^20.3.2",
    "@types/shelljs": "^0.8.12",
    "bottleneck": "^2.19.5",
    "glob": "^10.3.1",
    "sharp": "^0.32.1",
    "shelljs": "^0.8.5",
    "ts-node": "^10.9.1",
    "typescript": "^5.1.6"
  }
}
```

**Comment by GhostlyDark** [comment]
Thank you for posting that script.

I did some research in the meantime. By default, the conversion tool creates an OTR file that is compressed with zlib compression, which is the main reason as to why the game stutters a lot. The compression can be disabled with some simple changes. For some reason, SoH is unable to load an uncompressed OTR file, unless the `alt` path is used.

Going forward, only uncompressed archives will be used, which should make downscaling to very small sizes mostly obsolete.

**Comment by pakrett** [comment]
How do I use this script ?

**Comment by worstperson** [comment]
This was my converter implemented in python. I wanted to shrink the otr not for speed, but to fit on a fat32 partition for use on a Switch. Splitting the file as described issue #4 did not work for me for whatever reason. It's for Linux, but can probably be made to work in Windows by replacing the forward slashes with back slashes on line 7 and in the variable 'key'. It depends on Pillow which can be installed with pip or python-pillow from your distro's package manager.
```
import os, json
from PIL import Image

with open('manifest.json', 'r') as manifest:
  data = json.load(manifest)

path = os.getcwd() + '/'
lenth = len(data)
position = 1
converted = 0

for key in data:
    png = path + key + '.png'
    if os.path.isfile(png):
        print(str(position) + ' of ' + str(lenth) + ' - ' + key)
        image = Image.open(png)
        image = image.resize((data[key]['textureWidth'] * 4, data[key]['textureHeight'] * 4))
        image.save(png)
        converted += 1
    else:
        print(str(position) + ' of ' + str(lenth) + ' - ' + key + ' - SKIPPED')
    position += 1

print('Processed ' + str(converted) + ' textures')
```

**Comment by GhostlyDark** [comment]
For the sake of completeness, there's also this python script:
https://github.com/th-2021/scaled-ootr/tree/main

My personal favourite is the `underscale.sh` script however, that compares extracted/dumped files with the HD textures for rescaling (multithreaded):
https://github.com/R0CKH0PP3R/OoT

WSL is recommended by the author, but it can be used with MSYS2 on Windows. Only requires ImageMagick:
```
pacman -S mingw-w64-x86_64-imagemagick
```
Run the script:
```
./underscale.sh sd-folder hd-folder
```
Scale can be changed by editing the script file itself. This is the script that is currently used for the downscaled 8x release.
