### ISSUE TITLE
For the switch port of Ship of harkinian

### ISSUE THREAD

**Issue by pakrett** [GhostlyDark/OoT-Reloaded-SoH#4]
To use a switch with homebrews it's advised to format the sd card to fat32 for many reasons (exfat support on switch is not so good), the problem is that the OTR pack size is larger than 4gb and then can not be use with fat32, is it possible to split an OTR in 2 parts or more ? Or maybe make a texture pack with a lower resolution that makes the OTR smaller than 4gb ?

**Comment by GhostlyDark** [comment]
Yes, the files can be split for Switch. The procedure is the exact same as for copying large XCI/NSP files.
https://github.com/Aionmagan/NSPsplitty

Alternatively, one may download the downscaled ("1080p") textures and generate an OTR that uses compression via [retro](https://github.com/HarbourMasters64/retro/releases). The compressed OTR will be smaller than 4 GB, but stuttering will be an issue.

There is also a script posted [here](https://github.com/GhostlyDark/OoT-Reloaded-SoH/issues/4) to downscale the textures to a much lower size before generating the OTR.

**Comment by pakrett** [comment]
Oh ok thank you this is very convenient, I used nspsplitty and it works perfectly.
