### ISSUE TITLE
Weird/blurred Music Icons in Tracker

### ISSUE THREAD

**Issue by ThiagoSBarreto** [GhostlyDark/OoT-Reloaded-SoH#5]
![image](https://github.com/GhostlyDark/OoT-Reloaded-SoH/assets/30276822/694c2fac-2af2-41f4-b9e6-d2dc1866df77)

[OoT Reloaded (2160p OTR)]

bug with the songs icons on the tracker
on the menu they are fine.

**Comment by GhostlyDark** [comment]
Not a texture pack issue. This is a known Ship of Harkinian bug.
Possible workaround: Generate an OTR file with `alt/` path prepended.
