### ISSUE TITLE
Am I blind?

### ISSUE THREAD

**Issue by user18081972** [GhostlyDark/OoT-Reloaded-SoH#6]
I cannot tell the difference between 8x and the normal build on a 4k monitor.
Reloaded_8x otr
![Reloaded_8x otr](https://github.com/GhostlyDark/OoT-Reloaded-SoH/assets/124319511/65784224-9200-409c-8018-adeb3f285035)

Reloaded otr
![Reloaded otr](https://github.com/GhostlyDark/OoT-Reloaded-SoH/assets/124319511/21b8de29-d41e-4a21-98ea-a7a7df525b14)

Is it just me?

**Comment by GhostlyDark** [comment]
Some texture are the same, some are actually downscaled. On the screenshot, there isn't much different but the grass floor having less detail. A better comparison would be to check wooden floors that are resembling tree trunks, either in Kokiri Forest or Goron City, which showcases a much more apparent loss in detail.

For the following screenshots, only the wood texture has been downsampled to 8x - nothing else.

![image](https://github.com/GhostlyDark/OoT-Reloaded-SoH/assets/31742919/0af57c7d-ad3f-487f-b47a-d5ab87c58c52)
![image](https://github.com/GhostlyDark/OoT-Reloaded-SoH/assets/31742919/93a4d8ef-6001-453f-9fac-8006427bfbd5)
