### ISSUE TITLE
Newer version doesn't work and gets reduced to 1KB

### ISSUE THREAD

**Issue by Tasosgemah** [GhostlyDark/OoT-Reloaded-SoH#7]
I had an older version for a while that's also bigger in size. I don't remember the version number.

Anyway, i downloaded the newest version of the mod and replaced the older one. But now, not only the textures don't work, when i go to the folder where the textures mods are, this one gets reduced to 1KB... The emulator literally killed the file.

I had to get the old one from a backup, which works again. But the newer doesn't. It just gets reduced to 1KB every time i try to load the game.

**Comment by GhostlyDark** [comment]
This repository is for the PC port texture pack, not for any of the emulators. Make sure that the emulator/graphics plugin is up-to-date (GLideN64 latest WIP build, **`not`** the last stable release).

If you do require further help, I'd need more info. What emulator is it? What version is that emulator at? What plugins are you using? How old are those plugins? What settings are you using? What operating system? What files are you trying to load (HTS, HTS_0.5x?).

**Comment by Tasosgemah** [comment]
> This repository is for the PC port texture pack, not for any of the emulators. Make sure that the emulator/graphics plugin is up-to-date (GLideN64 latest WIP build, **`not`** the last stable release).
> 
> If you do require further help, I'd need more info. What emulator is it? What version is that emulator at? What plugins are you using? How old are those plugins? What settings are you using? What operating system? What files are you trying to load (HTS, HTS_0.5x?).

I'm using the .hts file that's supposed to be for GlideN64. Pretty sure this is only applicable for emulators, or so i thought.

I'm using RetroArch and Mupen64 plus-Next with GlideN64, the homepage (where the link is found here) also has instructions for this exact setup (that i followed). The operating system is Windows 10.

Thing is, i already did the job a few months ago, with a slightly older version of the HD pack. And i was playign with that. It was working. So the settings and everything else are correct. But if i overwrite the previous version of the HD pack with the newer one, i get the issue i posted about.

**Comment by Tasosgemah** [comment]
The front page says "Ocarina of Time Reloaded is an Ultra HD texture pack for [GLideN64](https://github.com/GhostlyDark/OoT-Reloaded), [Dolphin](https://github.com/GhostlyDark/OoT-Reloaded-Dolphin) and Ship of Harkinian." I'm using the .hts file that's supposed to be for GlideN64. Should i post this issue to the GlideN64 link above? I didn't realize it's three different repositories, sorry about that.

I'm using RetroArch and Mupen64 plus-Next with GlideN64, the homepage (where the link is found here) also has instructions for this exact setup (that i followed). The version of the core/plugin is the latest as of now, though i'm not sure how close it is to the source. The operating system is Windows 10.

Thing is, i already did the job a few months ago, with a slightly older version of the HD pack. And i was playign with that. It was working. So the settings and everything else are correct. But if i overwrite the previous version of the HD pack with the newer one, i get the issue i posted about.
